# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    environment:
      CC_TEST_REPORTER_ID: db8357071dbb10baa664dc536130ee05a50dda77a8e820664458ccd76ed4cd9d
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9-browsers
        # environment:
        #   CHROME_BIN: "/usr/bin/google-chrome"
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: npm rebuild node-sass

      # - run: npm install -g karma
        
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      # run tests!
      # - run: xvfb-run -a npm run test -- --single-run --no-progress --browser=ChromeNoSandbox
      # - run: xvfb-run -a npm run e2e -- --no-progress --config=protractor-ci.conf.js
      - run:
          name: Run unit tests with karma
          command: npm test
          # notify Code Climate of a pending test report using `before-build`
            ./cc-test-reporter before-build
            sudo vendor/bin/phpunit --coverage-clover clover.xml
          # upload test report to Code Climate using `after-build`
            ./cc-test-reporter after-build --coverage-input-type clover --exit-code $?
      #- run: npm test